import {Window} from 'happy-dom';import fs from 'node:fs';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';
const origin=process.env.PUNTO_TEST_ORIGIN||'http://127.0.0.1:8000',w=new Window({url:origin});let cookie='';w.alert=()=>{};w.confirm=()=>true;Object.defineProperty(w,'crypto',{value:webcrypto});w.structuredClone=structuredClone;
w.fetch=async(path,options={})=>{const r=await fetch(origin+path,{...options,headers:{...options.headers,Origin:origin,...(cookie?{Cookie:cookie}:{})}});const set=r.headers.get('set-cookie');if(set)cookie=set.split(';')[0];return r};
const html=fs.readFileSync(new URL('../static/index.html',import.meta.url),'utf8');w.document.write(html.split('<script>')[0]);w.eval(html.split('<script>')[1].split('</script>')[0]+';window.run=code=>eval(code);');await new Promise(r=>setTimeout(r,100));const $=s=>w.document.querySelector(s),submit=async selector=>$(selector).onsubmit({preventDefault(){},target:$(selector)});
async function login(user,password){w.run('showAuth()');$('[name=username]').value=user;$('[name=password]').value=password;await submit('#authform')}
await login('qa-admin','qa-admin-password-123');assert.equal(w.run('activeProfile.role'),'admin');w.run('page="Planes y cobros"');await w.run('billingAdmin()');$('[data-price=pro] [name=amount]').value='299';await submit('[data-price=pro]');assert.ok($('#requestlist'));
await w.run('logout()');w.run('showAuth(true)');$('[name=business]').value='Suscripciones QA';$('[name=username]').value='billing-'+Date.now();const user=$('[name=username]').value;$('[name=password]').value='test-pass-123456';$('[name=confirm]').value='test-pass-123456';await submit('#authform');
w.run('page="Suscripción"');await w.run('subscriptionPage()');assert.ok($('#view').textContent.includes('Prueba Pro'));assert.ok($('#view').textContent.includes('299.00'));await $('[data-plan=pro]').onclick();assert.ok($('[data-cancel]'));const rid=$('[data-cancel]').dataset.cancel;
await w.run('logout()');await login('qa-admin','qa-admin-password-123');w.run('page="Planes y cobros"');await w.run('billingAdmin()');await $(`[data-review="${rid}"]`).onclick();$('[name=reference]').value='QA-123';$('[name=note]').value='Pago de prueba confirmado';$('[name=confirmed]').checked=true;await submit('#decision');assert.ok($('#requestlist').textContent.includes('Aprobada'));assert.ok($('#requestlist').textContent.includes('QA-123'));
w.run('page="Administración"');await w.run('adminPanel()');await $('#audit').onclick();assert.ok($('#auditlist').textContent.includes('subscription.approve'));
await w.run('logout()');await login(user,'test-pass-123456');w.run('page="Suscripción"');await w.run('subscriptionPage()');assert.equal(w.run('activeProfile.business.plan'),'pro');assert.ok($('#view').textContent.includes('Aprobada'));
w.run('page="Reportes";reportsPage()');for(let i=0;i<100&&!$('#reportresult').textContent;i++)await new Promise(r=>setTimeout(r,20));assert.ok($('#reportresult').textContent.includes('Ticket promedio'));assert.ok($('#reportcsv'));
console.log('PASS: precios, solicitud, aprobación, auditoría, plan actualizado y reportes desde la interfaz.');await w.happyDOM.abort();
